name: Markdown Links Check
# runs every monday at 9 am
on:
  push:
    branches:
    - master
  schedule:
    - cron: "0 9 * * 1"

jobs:
  check-links:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: gaurav-nelson/github-action-markdown-link-check@v1
        with:
          use-quiet-mode: 'yes'
          use-verbose-mode: 'yes'
          config-file: '.github/workflows/markdown.links.config.json'
